/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class flappy_CodeInterpreter */

#ifndef _Included_flappy_CodeInterpreter
#define _Included_flappy_CodeInterpreter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     flappy_CodeInterpreter
 * Method:    evalPythonCode
 * Signature: (Lflappy/CodeInterpreter;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_flappy_CodeInterpreter_evalPythonCode
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
