flag_management:
  default_rules:
    carryforward: true
coverage:
  status:
    patch: off
    project: off
flags:
  rust:
    paths:
      - packages/rust-core/
  nodejs:
    paths:
      - packages/nodejs/
  kotlin:
    paths:
      - packages/kotlin/
  csharp:
    paths:
      - packages/csharp/

github_checks:
    annotations: true

comment:
  layout: "header, diff, flags, files, reach, footer"
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false        # [yes :: must have a base report to post]
  require_head: true       # [yes :: must have a head report to post]
  show_carryforward_flags: true
  show_critical_paths: true #new option to labeled critical files
  hide_comment_details: false #collapse all the "detailed info" for the PR comment
