flag_management:
  default_rules:
    carryforward: true
coverage:
  status:
    # It's noisey to have failed checks on PRs.
    # Because we already have Codecov bot commenting on PRs, here we disable the status check.
    project: off
    patch: off
flags:
  nodejs:
    paths:
      - packages/nodejs/
  kotlin:
    paths:
      - packages/kotlin/
  csharp:
    paths:
      - package/csharp/