/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package flappy

import com.fasterxml.jackson.annotation.JsonInclude
import kotlin.test.Test
import kotlin.test.assertEquals

private class MapperTest {

  @Test
  fun mapper2() {
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    data class Opt(
      val xxx: String? = null,

      val y: String = "123",

      val obj: Any? = object {
        val answer = "123"
      },

      val sss: String = "",

      val none: Any? = null,

      val map: Map<String, Int> = mapOf(Pair("foo", 1), Pair("bar", 2))
    ) {
      val foobar = "123132"
    }

    assertEquals(
      object {
        val a = 1
      }.asJSON(true).toUniversal(), """{
  "a": 1
}""".toUniversal()
    )

    assertEquals(Opt().asJSON(), """{"y":"123","obj":{"answer":"123"},"map":{"foo":1,"bar":2},"foobar":"123132"}""")
    assertEquals(
      Opt().asJSON(true).toUniversal(),
      """{
  "y": "123",
  "obj": {
    "answer": "123"
  },
  "map": {
    "foo": 1,
    "bar": 2
  },
  "foobar": "123132"
}""".toUniversal()
    )

  }

}
