name: Gradle publish

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'flappy/gradle.properties'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    timeout-minutes: 30
    environment:
      name: Maven
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Metadata
        id: metadata
        uses: ./.github/workflows/metadata

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Generate Changelog
        run: echo "# ${{steps.metadata.outputs.version}} ${{steps.metadata.outputs.build_date}}" > ${{ github.workspace }}-CHANGELOG.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          name: ${{steps.metadata.outputs.version}}
          tag_name: ${{steps.metadata.outputs.version}}

      - name: Run publish with Gradle
        run: ./gradlew publishAllPublicationsToGitHubPackageRepository
        env:
          ORG_GRADLE_PROJECT_GithubPackagesUsername: ${{vars.GPR_USERNAME}}
          ORG_GRADLE_PROJECT_GithubPackagesPassword: ${{secrets.GPR_TOKEN}}

      - name: Publish document
        run: ./gradlew dokkaHtml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: flappy/build/dokka/dokkaHtml