[package]
name = "flappy-nodejs-bindings"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[package.metadata.workspaces]
independent = true

[lib]
crate-type = ["cdylib"]

[dependencies]
flappy-common = { path = "../common", version = "*" }

mimalloc.workspace = true
openssl.workspace = true

napi = { version = "2", default-features = false, features = [
  "napi8",
  "async",
] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"
