[package]
name = "flappy-java-bindings"
version = "0.1.0"
edition = "2021"

[package.metadata.workspaces]
independent = true

[lib]
crate-type = ["cdylib"]

[dependencies]
flappy-common = { path = "../common" }
mimalloc = { version = "0.1.39", default-features = false }
jni = "0.21.1"
anyhow = "1.0.71"
num_cpus = "1.15.0"
once_cell = "1.17.1"
tokio = { version = "1.28.1", features = ["full"] }
opendal = "0.40.0"

[profile.release]
lto = true
codegen-units = 1

[profile.dev]
incremental = true
