[package]
name = "flappy-java-bindings"
version = "0.1.0"
edition = "2021"

[package.metadata.workspaces]
independent = true

[lib]
crate-type = ["cdylib"]
doc = false

[dependencies]
flappy-common = { path = "../common" }
mimalloc = { version = "0.1.39", default-features = false }
jni = "0.21.1"
anyhow = "1.0"
num_cpus = "1.16.0"
once_cell = "1.18.0"
tokio = { version = "1.32.0", features = [
  "sync",
  "macros",
  "time",
  "rt-multi-thread",
] }
openssl = { version = "0.10", features = ["vendored"] }

[profile.release]
lto = true
codegen-units = 1

[profile.dev]
incremental = true
