[package]
name = "flappy-java-bindings"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.workspaces]
independent = true

[lib]
crate-type = ["cdylib"]
doc = false

[dependencies]
flappy-common = { path = "../common", version = "*" }
mimalloc.workspace = true
anyhow.workspace = true
once_cell.workspace = true
num_cpus.workspace = true
openssl.workspace = true
tokio.workspace = true
thiserror.workspace = true

jni = "0.21.1"
