[package]
name = "flappy-core"
version = "0.1.0"
edition = "2021"

[package.metadata.workspaces]
independent = true


[dependencies]
deno_core = "0.218.0"
mimalloc = "0.1.38"
tokio = { version = "1.32.0", features = ["full"] }

