[package]
name = "flappy-common"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.workspaces]
independent = true


[dependencies]
anyhow.workspace = true
reqwest.workspace = true
tokio.workspace = true
once_cell.workspace = true
async-trait.workspace = true
futures.workspace = true
tracing.workspace = true
derivative.workspace = true

wasmer = "4.2.3"
wasmer-registry = "5.9.0"
wasmer-vm = "4.2.3"
wasmer-cache = { version = "4.2.3", features = ["blake3-pure"] }
wasmer-wasix = { version = "0.16.0", features = [
  "sys",
  "sys-poll",
  "logging",
  "host-fs",
  "host-vnet",
  "host-reqwest",
  "host-threads",
  "sys",
  "sys-thread",
] }
virtual-mio = { version = "0.3.0" }
dirs = "5.0.1"

webc = "5.8.0"
virtual-fs = { version = "0.9.0", features = ["host-fs"] }
virtual-net = { version = "0.6.1", features = ["host-net"] }
