[package]
name = "flappy-common"
version = "0.1.0"
description = ""

edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

publish = false

[package.metadata.workspaces]
independent = true


[dependencies]
anyhow.workspace = true
reqwest.workspace = true
tokio.workspace = true
once_cell.workspace = true
async-trait.workspace = true
futures.workspace = true
tracing.workspace = true
derivative.workspace = true
wasmer = "4.2.4"
wasmer-registry = "5.10.0"
wasmer-vm = "4.2.4"
wasmer-cache = { version = "4.2.4", features = ["blake3-pure"] }
wasmer-wasix = { version = "0.17.0", features = [
  "sys",
  "sys-poll",
  "logging",
  "host-fs",
  "host-vnet",
  "host-reqwest",
  "host-threads",
  "sys",
  "sys-thread",
] }
virtual-mio = { version = "0.3.0" }
dirs = "5.0.1"

webc = "5.8.1"
virtual-fs = { version = "0.10.0", features = ["host-fs"] }
virtual-net = { version = "0.6.1", features = ["host-net"] }
openssl.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = ["openssl"]

[lints]
workspace = true
