[package]
name = "flappy-csharp-bindings"
version = "0.1.0"
edition = "2021"

[package.metadata.workspaces]
independent = true

[lib]
crate-type = ["cdylib"]

[dependencies]
flappy-common = { path = "../common" }
mimalloc = { version = "0.1.39", default-features = false }
libc = "0.2"
tokio = { version = "1.33.0", features = ["full"] }
openssl = { version = "0.10", features = ["vendored"] }
serde = "1.0"
serde_json = "1.0"

[profile.release]
lto = true
codegen-units = 1
strip = true

[profile.dev]
incremental = true
