[package]
name = "flappy-csharp-bindings"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false


[package.metadata.workspaces]
independent = true

[lib]
crate-type = ["cdylib"]

[dependencies]
flappy-common = { path = "../common", version = "*" }
mimalloc.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true

libc = "0.2"
