[package]
name = "flappy-core"
description = "flappy core"
version = "0.1.0"

edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

publish = false

[dependencies]
