[package]
name = "flappy-llm"
version = "0.1.0"
description = ""
keywords = ["llm", "langchain", "chain"]

edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true

publish = false

[package.metadata.workspaces]
independent = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
async-trait.workspace = true
tokio.workspace = true
futures.workspace = true

mustache = { version = "0.9.0" }
llm-chain = { version = "0.13.0" }
llm-chain-mock = { version = "0.13.0" }
llm-chain-openai = { version = "0.13.0", optional = true }
llm-chain-local = { version = "0.12.3", optional = true }

[features]
openai = ["dep:llm-chain-openai"]
local = ["dep:llm-chain-local"]
default = ["openai", "local"]

# https://github.com/rustformers/llm#using-llm-in-a-rust-project
[profile.dev.package.ggml-sys]
opt-level = 3
