using Pleisto.Flappy.LLM;

namespace Pleisto.Flappy.Interfaces
{
  /// <summary>
  /// FlappyAgent Config
  /// </summary>
  public class FlappyAgentConfig
  {
    /// <summary>
    /// Which language model to use for inference.
    /// </summary>
    public ILLMBase LLM { get; set; }

    /// <summary>
    /// Which language model to use for planning.
    /// If not specified, use `llm` instead.
    /// </summary>
    public ILLMBase LLMPlaner { get; set; }

    /// <summary>
    /// Code interpreter could be used to execute code snippets in sandbox which are generated by language model.
    /// If not specified, this feature will be disabled.
    /// </summary>
    public FlappyAgentConfigCodeInterpreter? CodeInterpreter { get; set; }

    /// <summary>
    /// Maximum number of retries when language model generation failed.
    /// </summary>
    //[AllowNull]
    public int? Retry { get; set; }

    /// <summary>
    /// Functions
    /// </summary>
    public IFlappyFunction[] Functions { get; set; }
  }
}
