on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    name: 'Cleanup After PR Closed'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Cancel build runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          ignore_sha: true
          workflow_id: all
