name: Codegen

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'yarn.lock'
      - 'tools/devkit/**'
      - 'templates/**'
  push:
    branches: [main]
    paths:
      - 'yarn.lock'
      - 'tools/devkit/**'
      - 'templates/**'

jobs:
  nodejs-template-codegen-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: validate
        run: yarn dev ts-mustache-codegen
