name: CSharp Nuget CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'examples/csharp/**'
      - 'packages/csharp/**'
      - '.github/workflows/csharp-ci.yml'
  push:
    branches: [main]
    paths:
      - 'examples/csharp/**'
      - 'packages/csharp/**'
      - '.github/workflows/csharp-ci.yml'


jobs:
  tests:
    name: csharp-ci-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          #- windows-latest
          #- macos-latest
        dotnet-version:
          - framework: netcoreapp3.1
            runtime: 3.1
          - framework: net6.0
            runtime: 6.0
          - framework: net7.0
            runtime: 7.0
    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version.runtime }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: ${{ matrix.os }}-cargo

      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: actions/checkout@v4

      - name: build binding native
        run: |
          cd packages/rust-core/csharp
          cargo build

      - name: dotnet test
        run: |
          cd packages/csharp
          mkdir -p ./Pleisto.Flappy.Test/bin/Debug/${{ matrix.dotnet-version.framework }}/
          cp ../rust-core/target/debug/*csharp* ./Pleisto.Flappy.Test/bin/Debug/${{ matrix.dotnet-version.framework }}/
          dotnet test -e NO_GPT_TEST=true --framework ${{ matrix.dotnet-version.framework }}
