name: CSharp Nuget Test

on:
  workflow_dispatch:
  push:
    path:
      - "**/*.cs"
      - "**/*.csproj"
      - "**/*.sln"
      - "examples/csharp/**/*"
      - "packages/csharp/**/*"

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1
            6.0
            7.0
          source-url: https://nuget.pkg.github.com/pleisto/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - uses: actions/checkout@v4
      - name: Run Nuget Publish
        run: |
          cd packages/csharp;
          dotnet test