name: CSharp Bindings Publish


on:
  workflow_dispatch:
  push:
    #### TODO
    # paths:
    #   - 'packages/rust-core/charp/**'

defaults:
  run:
    working-directory: packages/rust-core/csharp

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  compile-binding:
    runs-on: ${{ matrix.os }}
    timeout-minutes:  60
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            classifier: linux-x86_64
          - os: windows-latest
            classifier: windows-x86_64
          - os: macos-latest
            classifier: osx-x86_64
          - os: macos-latest
            classifier: osx-aarch_64

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          python3 tools/build.py --classifier ${{ matrix.classifier }} --profile release


      - name: Upload local staging directory
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.classifier }}-local-staging
          path: packages/rust-core/csharp/target/bindings
          if-no-files-found: error

  publish-binding:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [ "compile-binding" ]
    steps:
      - uses: actions/checkout@v4


      # Download artifacts
      - name: Prepare environment variables
        run: echo "LOCAL_STAGING_DIR=$HOME/local-staging" >> $GITHUB_ENV

      - name: Download windows staging directory
        uses: actions/download-artifact@v3
        with:
          name: windows-x86_64-local-staging
          path: ~/windows-x86_64-local-staging
      - name: Download linux staging directory
        uses: actions/download-artifact@v3
        with:
          name: linux-x86_64-local-staging
          path: ~/linux-x86_64-local-staging
      - name: Download darwin staging directory
        uses: actions/download-artifact@v3
        with:
          name: osx-x86_64-local-staging
          path: ~/osx-x86_64-local-staging
      - name: Download darwin (aarch64) staging directory
        uses: actions/download-artifact@v3
        with:
          name: osx-aarch_64-local-staging
          path: ~/osx-aarch_64-local-staging

      # Generate nupkg
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1
            6.0
            7.0

      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.GITHUB_TOKEN }}

      - name: generate nupkg
        run: |
          dotnet build tools/Pleisto.Flappy.Native.csproj -o app/


      - name: dotnet publish
        run: |
          dotnet build -c Release
          find -type f | grep nupkg$ | grep -v 'symbols\.nupkg$' | while read line; do
            echo "Pulish: $line"
            nuget push $line \
              -Source https://api.nuget.org/v3/index.json \
              -ApiKey ${{ secrets.NUGET_TOKEN }} \
              -SkipDuplicate
          done