name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: 'Hello @${{ github.actor }}, thanks for opening your first pull request 😊! We really appreciate your work. Happy Coding 🎉🎊 !'
          issue-message: |
            Hello @${{ github.actor }}, thanks for your first issue and interest in our work 😊!
