name: Java Bindings Test

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/rust-core/common/**'
      - 'packages/rust-core/java/**'
      - 'packages/rust-core/Cargo.toml'
      - '.github/workflows/java-bindings-test.yml'

defaults:
  run:
    working-directory: packages/rust-core/java

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Set up JDK 8
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'

      - name: Install
        run: ./mvnw clean install -DskipTests -Dgpg.skip

      - name: Test
        run: ./mvnw verify -Dgpg.skip
