name: Java Bindings Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/rust-core/common/**'
      - 'packages/rust-core/java/**'
      - 'packages/rust-core/Cargo.toml'
      - '.github/workflows/java-bindings-test.yml'
      - '.github/workflows/java-bindings-publish-common.yml'
  push:
    paths:
      - 'packages/rust-core/common/**'
      - 'packages/rust-core/java/**'
      - 'packages/rust-core/Cargo.toml'
      - '.github/workflows/java-bindings-test.yml'
      - '.github/workflows/java-bindings-publish-common.yml'

defaults:
  run:
    working-directory: packages/rust-core/java

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Java Bindings Lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'

      - name: Install
        run: ./mvnw clean compile spotless:check -DskipTests -D"gpg.skip"

  publish:
    uses: ./.github/workflows/java-bindings-publish-common.yml
    with:
      publish: false

  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    name: Java Bindings Test ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'

      - name: Install
        run: ./mvnw clean install -DskipTests -D"gpg.skip"

      - name: Test
        # `mvn install` and `mvn artifact:compare` are required to verify reproducible builds:
        # https://maven.apache.org/guides/mini/guide-reproducible-builds.html#how-to-test-my-maven-build-reproducibility
        run: ./mvnw verify artifact:compare -D"gpg.skip"
