name: Kotlin Test

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.kt'
      - '**/*.kts'
      - '**/*.java'
      - '.github/workflows/kotlin-test.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 19 ]
        kotlin-version: [ 1.9.10 ]
        kotlin-ir-enabled: [ true ]
        kotlin-test-mode: [ 'REFLECT' ]
        # kotlin-test-mode: [ 'REFLECT', 'KSP', 'KAPT' ]
    name: "[java=${{ matrix.java-version }}, kotlin=${{ matrix.kotlin-version }}, IR=${{ matrix.kotlin-ir-enabled }}]"
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Run tests with Gradle
        run: >
          cd packages/kotlin && ./gradlew build check
          --stacktrace
          -Pkotlin.version=${{ matrix.kotlin-version }}
          -Pkotlin.ir.enabled=${{ matrix.kotlin-ir-enabled }}
          -PjavaToolchainTestVersion=${{ matrix.java-version }}
          -PkotlinTestMode=${{ matrix.kotlin-test-mode }}
