name: Kotlin Test

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/kotlin/**'
      - 'examples/kotlin/**'
      - 'examples/java/**'
      - '.github/workflows/kotlin-test.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: packages/kotlin

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        java-version: [11, 17, 21]
        kotlin-version: [1.9.10]
        kotlin-ir-enabled: [true]
        kotlin-test-mode: ['REFLECT']
        include:
          - os: ubuntu-latest
            excludeJniTests: false
          - os: macos-latest
            excludeJniTests: true
          - os: windows-latest
            excludeJniTests: true
        # kotlin-test-mode: [ 'REFLECT', 'KSP', 'KAPT' ]
    name: '<${{ matrix.os }}> [java=${{ matrix.java-version }}, kotlin=${{ matrix.kotlin-version }}, IR=${{ matrix.kotlin-ir-enabled }}]'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-version: wrapper

      - name: Run tests with Gradle
        run: >
          ./gradlew build check
          --stacktrace
          -P"excludeJniTests=${{ matrix.excludeJniTests }}"
          -P"kotlin.version=${{ matrix.kotlin-version }}"
          -P"kotlin.ir.enabled=${{ matrix.kotlin-ir-enabled }}"
          -P"javaToolchainTestVersion=${{ matrix.java-version }}"
          -P"kotlinTestMode=${{ matrix.kotlin-test-mode }}"
