name: Kotlin Publish

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: 'type'
        options:
          - all
          - github-package-only
          - maven-central-only
  push:
    branches: [main]
    paths:
      - 'packages/kotlin/flappy/gradle.properties'

defaults:
  run:
    working-directory: packages/kotlin

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Maven
    timeout-minutes: 30
    environment:
      name: Maven
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-version: wrapper

      - name: Publish document
        run: ./gradlew dokkaHtml

      - name: Publish to maven central
        run: ./gradlew publishAllPublicationsToMavenCentral --no-configuration-cache
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.type == 'all' || github.event.inputs.type == 'maven-central-only' }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY}}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD}}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{vars.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME}}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD}}

      - name: Publish to github packages
        run: ./gradlew publishAllPublicationsToGitHubPackageRepository
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.type == 'all' || github.event.inputs.type == 'github-package-only' }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY}}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD}}
          ORG_GRADLE_PROJECT_GithubPackagesUsername: ${{vars.ORG_GRADLE_PROJECT_GITHUBPACKAGESUSERNAME}}
          ORG_GRADLE_PROJECT_GithubPackagesPassword: ${{secrets.ORG_GRADLE_PROJECT_GITHUBPACKAGESPASSWORD}}

