name: Nodejs Bindings Build Common for Workflow Calling Only

env:
  DEBUG: napi:*
  APP_NAME: flappy-nodejs-bindings
  MACOSX_DEPLOYMENT_TARGET: '10.13'
  WORKING_DIRECTORY: packages/rust-core/nodejs

permissions:
  contents: write
  id-token: write

defaults:
  run:
    working-directory: packages/rust-core/nodejs

on:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            build: yarn build:nodejs-bindings --target x86_64-apple-darwin

          - host: macos-latest
            target: aarch64-apple-darwin
            build: yarn build:nodejs-bindings --target aarch64-apple-darwin

          - host: ubuntu-latest
            target: x86_64-pc-windows-gnu
            command: sudo apt-get install -y gcc-mingw-w64-x86-64-win32 && cargo install cargo-xwin
            build: yarn build:nodejs-bindings --target x86_64-pc-windows-gnu

          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: yarn build:nodejs-bindings --target x86_64-unknown-linux-gnu

          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            build: yarn build:nodejs-bindings --target x86_64-unknown-linux-musl

          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build: yarn build:nodejs-bindings --target aarch64-unknown-linux-gnu

          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            build: yarn build:nodejs-bindings --target aarch64-unknown-linux-musl

          - host: ubuntu-latest
            target: aarch64-linux-android
            build: yarn build:nodejs-bindings --target aarch64-linux-android

    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: yarn

      - name: Run command ${{matrix.settings.command}}
        if: ${{matrix.settings.command}}
        run: ${{matrix.settings.command}}

      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.target }}

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{matrix.settings.target}}

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: ${{ matrix.settings.build }}
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bindings-${{ matrix.settings.target }}
          path: ${{ env.WORKING_DIRECTORY }}/${{ env.APP_NAME }}.*.node
          if-no-files-found: error
  universal-macOS:
    name: nodejs-bindings-ci-build-universal-macos
    needs:
      - build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Download macOS x64 artifact
        uses: actions/download-artifact@v3
        with:
          name: bindings-x86_64-apple-darwin
          path: packages/rust-core/nodejs/artifacts
      - name: Download macOS arm64 artifact
        uses: actions/download-artifact@v3
        with:
          name: bindings-aarch64-apple-darwin
          path: packages/rust-core/nodejs/artifacts
      - name: Combine binaries
        run: yarn universal
        working-directory: packages/rust-core/nodejs
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bindings-universal-apple-darwin
          path: ${{ env.WORKING_DIRECTORY }}/${{ env.APP_NAME }}.*.node
          if-no-files-found: error
