name: Nodejs CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  actions: read
  contents: read
  security-events: write

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'yarn.lock'
      - 'packages/nodejs/**'
      - '.github/workflows/nodejs-build-common.yml'
      - '.github/workflows/nodejs-ci.yml'
      - '.github/workflows/codeql.yml'
      - 'templates/**'
  push:
    branches: [main]
    paths:
      - 'yarn.lock'
      - 'packages/nodejs/**'
      - '.github/workflows/nodejs-build-common.yml'
      - '.github/workflows/nodejs-ci.yml'
      - '.github/workflows/codeql.yml'
      - 'templates/**'
jobs:
  publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - run: npm publish --dry-run
        working-directory: ./packages/nodejs
  codeql:
    name: nodejs-ci-codeql
    uses: ./.github/workflows/codeql.yml
    with:
      language: javascript-typescript
      working-directory: packages/nodejs
  build:
    name: nodejs-ci-build
    uses: ./.github/workflows/nodejs-build-common.yml
  lint:
    name: nodejs-ci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
        working-directory: ./packages/nodejs
  test:
    name: nodejs-ci-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Test
        run: yarn coverage
        working-directory: ./packages/nodejs

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          working-directory: ./packages/nodejs
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          flags: nodejs
          fail_ci_if_error: true
          verbose: true
