name: Nodejs Bindings Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: packages/rust-core/nodejs

env:
  WORKING_DIRECTORY: packages/rust-core/nodejs

permissions:
  contents: write
  id-token: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'packages/rust-core/nodejs/package.json'
      - '.github/workflows/nodejs-bindings-build.yml'
      - '.github/workflows/nodejs-bindings-publish.yml'

jobs:
  check_if_need_release:
    name: nodejs-bindings-publish-version-check
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.compare_version.outputs.release }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          check-latest: true
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Compare version
        id: compare_version
        run: |
          new_version=$(node -p "require('./package.json').version")
          versions=$(npm view @pleisto/flappy-nodejs-bindings versions)
          echo "current version: $new_version"
          echo $versions
          if [ -z "${versions[@]}" ]; then
            echo "version is empty"
            exit 1
          fi

          if [[ "${versions[@]}" =~ "${new_version}" ]]; then
            echo "Version is exist."
            echo "release=no" >> "$GITHUB_OUTPUT"
          else
            echo "Version is not exist."
            echo "release=yes" >> "$GITHUB_OUTPUT"
          fi
  build:
    name: nodejs-bindings-publish-build
    needs: [check_if_need_release]
    if: needs.check_if_need_release.outputs.release == 'yes'
    uses: ./.github/workflows/nodejs-bindings-build.yml
  publish:
    name: nodejs-bindings-publish-release
    needs: [check_if_need_release, build]
    if: needs.check_if_need_release.outputs.release == 'yes'
    runs-on: ubuntu-latest
    environment:
      name: Npm
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          check-latest: true
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{env.WORKING_DIRECTORY}}/artifacts
      - name: Move artifacts
        run: yarn artifacts
      - name: List packages
        run: ls -R ./npm
        shell: bash
      - name: Publish
        run: |
          if node -p "require('./package.json').version" | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
          then
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
            npm publish --access public
          elif node -p "require('./package.json').version" | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+";
          then
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
            npm publish --tag next --access public
          else
            echo "Not a release, skipping publish"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
