name: Nodejs Build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'yarn.lock'
      - 'packages/nodejs/**'
      - '.github/workflows/nodejs-build-common.yml'
      - '.github/workflows/nodejs-build.yml'
  push:
    branches: [main]
    paths:
      - 'yarn.lock'
      - 'packages/nodejs/**'
      - '.github/workflows/nodejs-build-common.yml'
      - '.github/workflows/nodejs-build.yml'

jobs:
  build:
    name: nodejs-ci-build
    uses: ./.github/workflows/nodejs-build-common.yml
