name: Nodejs Build Common for Workflow Call Only

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      - name: Install yarn dependencies
        run: yarn install --immutable

      - name: Run build
        run: yarn build:nodejs
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: nodejs-build
          path: packages/nodejs/dist
          if-no-files-found: error
