name: Nodejs CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'yarn.lock'
      - 'packages/nodejs/**'
      - '.github/workflows/nodejs-build-common.yml'
      - '.github/workflows/nodejs-ci.yml'
  push:
    branches: [main]
    paths:
      - 'yarn.lock'
      - 'packages/nodejs/**'
      - '.github/workflows/nodejs-build-common.yml'
      - '.github/workflows/nodejs-ci.yml'

jobs:
  build:
    name: nodejs-ci-build
    uses: ./.github/workflows/nodejs-build-common.yml
