name: Nodejs Publish

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

defaults:
  run:
    working-directory: packages/nodejs

env:
  WORKING_DIRECTORY: packages/nodejs

permissions:
  contents: write
  id-token: write

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main
    paths:
      - 'packages/nodejs/src/**'
      - 'packages/nodejs/tsconfig.json'
      - 'packages/nodejs/package.json'
      - '.github/workflows/nodejs-build.yml'
      - '.github/workflows/nodejs-publish.yml'

jobs:
  check_if_need_release:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.compare_version.outputs.release }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          check-latest: true
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Compare version
        id: compare_version
        run: |
          new_version=$(node -p "require('./package.json').version")
          versions=$(npm view @pleisto/node-flappy versions)
          echo "current version: $new_version"
          echo $versions
          if [ -z "${versions[@]}" ]; then
            echo "version is empty"
            exit 1
          fi

          if [[ "${versions[@]}" =~ "${new_version}" ]]; then
            echo "Version is exist."
            echo "release=no" >> "$GITHUB_OUTPUT"
          else
            echo "Version is not exist."
            echo "release=yes" >> "$GITHUB_OUTPUT"
          fi
  stage-snapshot:
    needs: [check_if_need_release]
    if: needs.check_if_need_release.outputs.release == 'yes'
    uses: ./.github/workflows/nodejs-build.yml
  publish:
    needs: [check_if_need_release, stage-snapshot]
    if: needs.check_if_need_release.outputs.release == 'yes'
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          check-latest: true
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Publish
        run: |
          if node -p "require('./package.json').version" | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
          then
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
            npm publish --access public
          elif node -p "require('./package.json').version" | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+";
          then
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
            npm publish --tag next --access public
          else
            echo "Not a release, skipping publish"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
