name: Nodejs Bindings Build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

env:
  DEBUG: napi:*
  APP_NAME: flappy-nodejs-bindings
  MACOSX_DEPLOYMENT_TARGET: '10.13'
  WORKING_DIRECTORY: packages/rust-core/nodejs

permissions:
  contents: write
  id-token: write

defaults:
  run:
    working-directory: packages/rust-core/nodejs

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'yarn.lock'
      - 'packages/rust-core/common/**'
      - 'packages/rust-core/nodejs/**'
      - 'packages/rust-core/Cargo.toml'
      - 'packages/rust-core/Cargo.lock'
      - 'packages/rust-core/package.json'
      - '.github/workflows/nodejs-bindings-build-common.yml'
      - '.github/workflows/nodejs-bindings-build.yml'
  push:
    branches: [main]
    paths:
      - 'yarn.lock'
      - 'packages/rust-core/common/**'
      - 'packages/rust-core/nodejs/**'
      - 'packages/rust-core/Cargo.toml'
      - 'packages/rust-core/Cargo.lock'
      - 'packages/rust-core/package.json'
      - '.github/workflows/nodejs-bindings-build-common.yml'
      - '.github/workflows/nodejs-bindings-build.yml'

jobs:
  build:
    name: nodejs-bindings-ci-build
    uses: ./.github/workflows/nodejs-bindings-build-common.yml
