name: Nodejs Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/nodejs/src/**'
      - 'packages/nodejs/tsconfig.json'
      - 'packages/nodejs/package.json'
      - 'packages/nodejs/yarn.lock'
      - '.github/workflows/nodejs-build.yml'
  push:
    paths:
      - 'packages/nodejs/src/**'
      - 'packages/nodejs/tsconfig.json'
      - 'packages/nodejs/package.json'
      - 'packages/nodejs/yarn.lock'
      - '.github/workflows/nodejs-build.yml'

jobs:
  build:
    name: Nodejs Building
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Detect what files changed
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: |
            src_or_deps_changed:
              - 'packages/nodejs/src/**'
              - '**/*.[tj]{s,sx}'
              - 'packages/nodejs/package.json'
              - '**/yarn.lock'
      - name: Install yarn dependencies
        if: steps.changes.outputs.src_or_deps_changed == 'true'
        run: yarn install --immutable
        shell: bash
      - name: Run build
        if: steps.changes.outputs.src_or_deps_changed == 'true'
        run: yarn build:nodejs
