name: Gradle publish

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: 'type'
        options:
          - all
          - github-page-only
          - github-package-only
          - maven-central-only
  push:
    branches: [main]
    paths:
      - 'packages/kotlin/flappy/gradle.properties'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Maven
    timeout-minutes: 30
    environment:
      name: Maven
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish document
        run: ./gradlew dokkaHtml
        working-directory: packages/kotlin

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.type == 'all' || github.event.inputs.type == 'github-page-only' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: kotlin
          publish_dir: packages/kotlin/flappy/build/dokka/dokkaHtml

      - name: Publish to maven central
        run: ./gradlew publishAllPublicationsToMavenCentral --no-configuration-cache
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.type == 'all' || github.event.inputs.type == 'maven-central-only' }}
        working-directory: packages/kotlin
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY}}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD}}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD}}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{vars.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME}}

      - name: Publish to github packages
        run: ./gradlew publishAllPublicationsToGitHubPackageRepository
        working-directory: packages/kotlin
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.type == 'all' || github.event.inputs.type == 'github-package-only' }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY}}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD}}
          ORG_GRADLE_PROJECT_GithubPackagesUsername: ${{vars.ORG_GRADLE_PROJECT_GITHUBPACKAGESUSERNAME}}
          ORG_GRADLE_PROJECT_GithubPackagesPassword: ${{secrets.ORG_GRADLE_PROJECT_GITHUBPACKAGESPASSWORD}}

