name: Rust CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/rust-core/**'
      - '.github/workflows/rust-ci.yml'
  push:
    branches: [main]
    paths:
      - 'packages/rust-core/**'
      - '.github/workflows/rust-ci.yml'

env:
  RUST_BACKTRACE: full
  CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG: true
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  RUST_LOG: debug

defaults:
  run:
    working-directory: packages/rust-core

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Generate lockfile
        run: cargo generate-lockfile

      - name: Audit dependencies
        run: cargo audit

  lint:
    name: rust-ci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: fmt
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  windows-test:
    name: rust-ci-test-windows
    runs-on: windows-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4

      - name: Setup Choco and perl
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install -y strawberryperl

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --profile=test

      # - name: Test
      #   run: cargo test --verbose -- --nocapture

  test:
    name: rust-ci-test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            test: true

          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl

          - os: macos-latest
            target: x86_64-apple-darwin
            test: true

          - os: macos-latest
            target: aarch64-apple-darwin

          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            command: sudo apt-get install -y gcc-mingw-w64-x86-64-win32 && cargo install cargo-xwin

    steps:
      - uses: actions/checkout@v4

      - name: Run command ${{ matrix.command }}
        if: ${{ matrix.command }}
        run: ${{ matrix.command }}

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --profile=test

      - name: Test
        if: ${{ matrix.test }}
        run: cargo test --verbose -- --nocapture
