name: Rust Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/rust-core/**'
      - '.github/workflows/rust-test.yml'
  push:
    branches: [main]
    paths:
      - 'packages/rust-core/**'
      - '.github/workflows/rust-test.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: full
  CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG: true
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  RUST_LOG: debug

defaults:
  run:
    working-directory: packages/rust-core

jobs:
  lint:
    name: rust-ci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: fmt
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy -- -D warnings

  tests:
    name: rust-ci-test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          # - os: macos-latest
          #   target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{matrix.target}}

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{matrix.target}}

      - name: Test
        run: cargo test --verbose
