[workspace]
members = ["./common", "./llm", "./nodejs", "./java", "./csharp"]
resolver = "2"


[workspace.package]
license = "Apache-2.0"
repository = "https://github.com/pleisto/flappy"
homepage = "https://flappy.pleisto.com"
edition = "2021"
keywords = []
categories = []

[workspace.dependencies]
mimalloc = { version = "0.1.39", default-features = false }
reqwest = { version = "0.11.22", default-features = false, features = [
  "gzip",
  "native-tls",
  "json",
  "multipart",
] }
tokio = { version = "1.34.0", features = [
  "sync",
  "macros",
  "time",
  "rt-multi-thread",
] }
tracing = "0.1.40"
once_cell = "1.18.0"
async-trait = "0.1.74"
futures = "0.3.29"
derivative = "2.2.0"
anyhow = "1.0.75"
thiserror = "1.0.50"
num_cpus = "1.16.0"
serde = "1.0.192"
serde_json = "1.0.108"
lazy_static = "1.4.0"
strum = "0.25.0"
strum_macros = "0.25.3"
derive_builder = "0.12.0"
openssl = { version = "0.10", features = ["vendored"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.release]
lto = true
codegen-units = 1
strip = true

[profile.test]
opt-level = 0
debug = true

[profile.dev]
incremental = true
