[workspace]
members = ["./common", "./llm", "./nodejs", "./java", "./csharp"]
resolver = "2"


[workspace.package]
license = "Apache-2.0"
repository = "https://github.com/pleisto/flappy"
homepage = "https://flappy.pleisto.com"
edition = "2021"
keywords = []
categories = []

[workspace.dependencies]
rand = "0.8.5"
mimalloc = { version = "0.1.39", default-features = false }
reqwest = { version = "0.11.22", default-features = false, features = [
  "gzip",
  "json",
  "multipart",
] }
reqwest-middleware = "0.2.4"
reqwest-retry = "0.3.0"
reqwest-tracing = "0.4.6"
tokio = { version = "1.34.0", features = [
  "sync",
  "macros",
  "time",
  "rt-multi-thread",
] }
tokio-stream = "0.1.14"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
once_cell = "1.18.0"
async-stream = "0.3.5"
bytes = "1.5.0"
async-trait = "0.1.74"
futures = "0.3.29"
derivative = "2.2.0"
anyhow = "1.0.75"
thiserror = "1.0.50"
num_cpus = "1.16.0"
serde = "1.0.193"
serde_json = "1.0.108"
lazy_static = "1.4.0"
secrecy = "0.8.0"
strum = "0.25.0"
strum_macros = "0.25.3"
derive_builder = "0.12.0"
enum_dispatch = "0.3.12"
spinoff = "0.8.0"
clap = { version = "4.4.10", features = ["derive"] }
openssl = { version = "0.10", features = ["vendored"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.release]
lto = true
codegen-units = 1
strip = true

[profile.test]
opt-level = 0
debug = true

[profile.dev]
incremental = true
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
